# Shotgun Pipeline Toolkit configuration file
# this file was automatically created

host: "https://shotgun.nikkigames.cn"
api_script: "Toolkit"
api_key: "hpNj(fdcetybf9tzccxiyywyb"
http_proxy: null

# End of file.
